PROJECT         := Test
DEVICES         := LPC11U24 NRF51822
#GCC4MBED_TYPE   := Debug
GCC4MBED_DIR    := ../..
NO_FLOAT_SCANF  := 1
NO_FLOAT_PRINTF := 1
#MBED_LIBS       := rtos

include $(GCC4MBED_DIR)/build/gcc4mbed.mk
