###############################
#       MetaWear Board        #
###############################

PROJECT         := MetaWear
DEVICES         := NRF51822
BUILD_TYPE      := Debug
WORKSPACE_ROOT  := ../..
MBED_LIBS       := rtos
INCDIRS         := $(WORKSPACE_ROOT)/mbed-src/libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib
INCDIRS         += $(WORKSPACE_ROOT)/mbed-src/libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/nrf-sdk/app_common

include $(WORKSPACE_ROOT)/build/mbed.mk
